version: "3.8"

services:
  server:
    build:
      context: ./server/
    restart: unless-stopped
    volumes:
      - ./server:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data